<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Command' => 'Dodaj polecenie',
    'Add Device' => 'Dodaj urządzenie',
    'Add User' => 'Dodaj użytkownika',
    'Added' => 'Dodano',
    'All rights reserved' => 'Wszelkie prawa zastrzeżone',
    'Are you sure you want to delete this command?' => 'Czy na pewno chcesz usunąć to polecenie?',
    'Are you sure you want to delete this device?' => 'Czy na pewno chcesz usunąć to urządzenie?',
    'Are you sure you want to delete this user?' => 'Czy na pewno chcesz usunąć tego użytkownika?',
    'Command' => 'Polecenie',
    'Commands' => 'Polecenia',
    'Control Panel' => 'Panel sterowania',
    'Copyright &copy; 2022-{current-year} by' => 'Prawa autorskie &copy; 2022-{current-year}',
    'Delete' => 'Usuń',
    'Details of selected command are provided below.' => 'Szczegóły wybranego polecenia podane są poniżej.',
    'Details of selected device are provided below.' => 'Szczegóły wybranego urządzenia podane są poniżej.',
    'Details of selected user are provided below.' => 'Szczegóły wybranego użytkownika podane są poniżej.',
    'Device' => 'Urządzenie',
    'Devices' => 'Urządzenia',
    'English' => 'English',
    'European Funds icons' => 'Ikony Funduszy Unijnych',
    'If you do not have an account, did not receive the verification email or have forgotten your password, please contact your system administrator. These kinds of situations must be solved manually.' => 'Jeśli nie posiadasz konta, e-mail weryfikacyjny nie dotarł lub nie pamiętasz hasła, skontaktuj się z administratorem systemu. Tego rodzaju sytuacje muszą być rozwiązane ręcznie.',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Innowacyjne rozwiązania w zakresie zdalnego monitorowania i rehabilitacji wad postawy',
    'Last contact' => 'Ostatni kontakt',
    'Login' => 'Logowanie',
    'Logout' => 'Wyloguj się',
    'Main Application' => 'Aplikacja główna',
    'Name and surname' => 'Imię i nazwisko',
    'Only logged-in users with administrator status have access to the backend. Login is also independent between the backend and the frontend. The person logged in to the backend must also log in to the backend.' => 'Dostęp do panelu sterowania mają tylko zalogowani użytkownicy o statusie administratora. Logowanie się jest też niezależne między panelem sterowania i aplikacją główną. Osoba zalogowana w aplikacji głównej musi dodatkowo zalogować się do panelu sterowania.',
    'Please contact us if you think this is a server error. Thank you.' => 'Jeśli uważasz, że jest to błąd serwera, skontaktuj się z nami. Dziękujemy.',
    'Please fill out the following fields to add a command.' => 'Aby dodać nowe polecenie, wypełnij poniższy formularz.',
    'Please fill out the following fields to add a device.' => 'Aby dodać nowe urządzenie, wypełnij poniższy formularz.',
    'Please fill out the following fields to add a user.' => 'Aby dodać nowego użytkownika, wypełnij poniższy formularz.',
    'Please fill out the following fields to login:' => 'Aby zalogować się, wypełnij poniższy formularz:',
    'Please use this form to update selected command.' => 'Aby zmienić dane wybranego polecenia, użyj poniższego formularza.',
    'Please use this form to update selected device.' => 'Aby zmienić dane wybranego urządzenia, użyj poniższego formularza.',
    'Please use this form to update selected user.' => 'Aby zmienić dane wybranego użytkownika, użyj poniższego formularza.',
    'Recently added devices' => 'Ostatnio dodane urządzenia',
    'Recently added users' => 'Ostatnio dodani użytkownicy',
    'Recently parsed commands' => 'Ostatnio przetworzone polecenia',
    'Save' => 'Zapisz',
    'Start' => 'Start',
    'The above error occurred while the Web server was processing your request.' => 'Powyższy błąd wystąpił podczas przetwarzania Twojego żądania przez serwer WWW.',
    'The list of all commands created in the system is shown below.' => 'Lista wszystkich poleceń utworzonych w systemie znajduje się poniżej.',
    'The list of all devices existing in the system is shown below.' => 'Lista wszystkich urządzeń istniejących w systemie znajduje się poniżej.',
    'The list of all users existing in the system is shown below.' => 'Lista wszystkich użytkowników istniejących w systemie znajduje się poniżej.',
    'This user' => 'Ten użytkownik',
    'This user has' => 'Ten użytkownik',
    'Update' => 'Edytuj',
    'Update Device: {name}' => 'Edytuj urządzenie: {name}',
    'User' => 'Użytkownik',
    'Users' => 'Użytkownicy',
    'Version' => 'Wersja',
    'View commands' => 'Przeglądaj polecenia',
    'View devices' => 'Przeglądaj urządzenia',
    'View users' => 'Przeglądaj użytkowników',
    'You can only delete a user that has' => 'Możesz usunąć jedynie takiego użytkownika, który',
    'You must assign all user\'s objects to some other user before deleting it.' => 'Musisz przypisać wszystkie obiekty danego użytkownika do innego, zanim go usuniesz.',
    'and' => 'i',
    'and therefore' => 'i dlatego',
    'can be deleted' => 'może zostać usunięty',
    'can login' => 'może zalogować się',
    'cannot be deleted' => 'nie może zostać usunięty',
    'cannot login' => 'nie może zalogować się',
    'is active' => 'jest aktywny',
    'is an administrator' => 'jest administratorem',
    'is not active' => 'jest nieaktywny',
    'is not an administrator' => 'nie jest administratorem',
    'no patients, no examinations and no results' => 'nie ma pacjentów, badań ani wyników',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'to backend' => 'do panelu sterowania',
    'to frontend' => 'do aplikacji głównej',
    '{p, plural, =0{no examinations} =1{# examination} other{# examinations}}' => '{p, plural, =0{nie ma badań} =1{ma # badanie} few{ma # badania} other{ma # badań}}',
    '{p, plural, =0{no patients} =1{# patient} other{# patients}}' => '{p, plural, =0{nie ma pacjentów} =1{ma # pacjenta} other{ma # pacjentów}}',
    '{p, plural, =0{no results} =1{# result} other{# results}}' => '{p, plural, =0{nie ma wyników} =1{ma # wynik} few{ma # wyniki} other{ma # wyników}}',
    'Русский' => 'Русский',
    'assigned to itself' => 'przypisanych do siebie',
];
