<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email address:' => 'Adres e-mail',
    'For the account' => 'Dla konta',
    'Have good day!' => 'Życzymy miłego dnia!',
    'Hello!' => 'Dzień dobry!',
    'If it was you then follow the link below to continue and reset your password:' => 'Jeśli to Ty, to użyj poniższego odnośnika, żeby zresetować swoje hasło:',
    'If it was you then follow the link below to verify your email address:' => 'Jeśli to Ty, to użyj poniższego odnośnika, żeby zweryfikować swój adres e-mail:',
    'If it wasn\'t you then you may safely ignore this message. Unverified email addresses are automatically removed from our system.' => 'Jeśli to nie Ty, to możesz zignorować tę wiadomość. Niezweryfikowane adresy e-mail są automatycznie usuwane z naszego systemu.',
    'If it wasn\'t you then you may safely ignore this message. Your password won\'t be changed.' => 'Jeśli to nie Ty, to możesz zignorować tę wiadomość. Twoje hasło nie ulegnie zmianie.',
    'Somebody has created an account in our website with the following data:' => 'Ktoś zarejestrował konto na naszej stronie internetowej, używając poniższych danych:',
    'The {app-name}\'s Team' => '{app-name}',
    'somebody has requested a password to the be reset.' => 'ktoś zażądał zresetowania hasła.',
    'Username:' => 'Nazwa użytkownika',
];
