<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktywny',
    'Administrator' => 'Administrator',
    'Auth Key' => 'Klucz uwierzytelniający',
    'Created At' => 'Data utworzenia',
    'Email Address' => 'Adres e-mail',
    'ID' => 'Identyfikator',
    'Inactive' => 'Nieaktywny',
    'Incorrect username or password.' => 'Nieprawidłowy login lub hasło.',
    'Password' => 'Hasło',
    'Password Hash' => 'Token szyfrowania hasła',
    'Password Reset Token' => 'Token resetowania hasła',
    'Regular' => 'Regularny',
    'Remember Me' => 'Zapamiętaj mnie',
    'Status' => 'Stan',
    'This email address has already been taken.' => 'Ten adres e-mail jest już zajęty.',
    'This field cannot be blank.' => 'To pole nie może pozostać puste.',
    'This username has already been taken.' => 'Ta nazwa użytkownika jest już zajęta.',
    'Type' => 'Typ',
    'Updated At' => 'Data aktualizacji',
    'Username' => 'Login',
    'Verification Token' => 'Token weryfikacyjny',
    'This field must contain a valid email address.' => 'To pole musi zawierać prawidłowy adres e-mail.',
];
