<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A web application for creating paragraph games and visual novels' => 'Aplikacja internetowa do tworzenia gier akapitowych i powieści wizualnych',
    'Add User' => 'Dodaj użytkownika',
    'All rights reserved' => 'Wszelkie prawa zastrzeżone',
    'Are you sure you want to delete this user?' => 'Czy na pewno chcesz usunąć tego użytkownika?',
    'Delete' => 'Usuń',
    'Details of selected user are provided below.' => 'Szczegóły wybranego użytkownika podane są poniżej.',
    'English' => 'English',
    'Forgotten password?' => 'Zapomniane hasło?',
    'Login' => 'Logowanie',
    'Please choose your new password:' => 'Proszę wybrać nowe hasło:',
    'Please contact us if you think this is a server error. Thank you.' => 'Jeśli uważasz, że jest to błąd serwera, skontaktuj się z nami. Dziękujemy.',
    'Please fill out the following fields to add a user.' => 'Aby dodać nowego użytkownika, wypełnij poniższy formularz.',
    'Please fill out your email. A link to reset password will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą zresetowanie hasła.',
    'Please fill out your email. A verification email will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą weryfikację tego adresu.',
    'Please use this form to update selected user.' => 'Aby zmienić dane wybranego użytkownika, użyj poniższego formularza.',
    'Request password reset' => 'Reset hasła',
    'Resend it' => 'Ponów wysyłkę',
    'Resend verification email' => 'Weryfikacja adresu e-mail',
    'Reset it' => 'Zresetuj je',
    'Reset password' => 'Reset hasła',
    'Save' => 'Zapisz',
    'Send' => 'Wyślij',
    'Start' => 'Start',
    'The above error occurred while the Web server was processing your request.' => 'Powyższy błąd wystąpił podczas przetwarzania Twojego żądania przez serwer WWW.',
    'The list of all users existing in the system is shown below.' => 'Lista wszystkich użytkowników istniejących w systemie znajduje się poniżej.',
    'The verification email did not arrive?' => 'Brak e-maila weryfikacyjnego?',
    'This user' => 'Ten użytkownik',
    'Update' => 'Edytuj',
    'User' => 'Użytkownik',
    'Users' => 'Użytkownicy',
    'Version' => 'Wersja',
    'You can only delete a user that has' => 'Możesz usunąć jedynie takiego użytkownika, który',
    'You do not have an account?' => 'Nie posiadasz konta?',
    'You must assign all user\'s objects to some other user before deleting it.' => 'Musisz przypisać wszystkie obiekty danego użytkownika do innego, zanim go usuniesz.',
    'and' => 'i',
    'assigned to itself' => 'przypisanych do siebie',
    'is active' => 'jest aktywny',
    'is not active' => 'jest nieaktywny',
    'no objects' => 'żadnych obiektów',
    'polski' => 'polski',
    'Log In' => 'Zaloguj się',
    'Log Out' => 'Wyloguj się',
    'Please fill out the following fields to log into this application.' => '',
    'Please fill out the following fields to sign up for a new account.' => '',
    'Sign Up' => 'Zarejestruj się',
    'can log in' => 'może się zalogować',
    'cannot log in' => 'nie może się zalogować',
    'for a new one' => '',
    'to this application' => '',
];
