<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Sign Up' => 'Rejestracja konta',
    'At least one active administrator is required in this application.' => 'W aplikacji musi być co najmniej jeden aktywny administrator.',
    'Email Address' => 'Adres e-mail',
    'Password' => 'Hasło',
    'Password Reset' => 'Reset hasła',
    'Password reset is available for verified accounts only.' => 'Resetowanie hasła jest dostępne tylko dla zweryfikowanych kont.',
    'Password reset token cannot be blank.' => 'Token resetowania hasła nie może być pusty.',
    'This email address has already been taken.' => 'Ten adres e-mail jest już zajęty.',
    'This field cannot be blank.' => 'To pole nie może pozostać puste.',
    'This field must contain a valid email address.' => 'To pole musi zawierać prawidłowy adres e-mail.',
    'This username has already been taken.' => 'Ta nazwa użytkownika jest już zajęta.',
    'Username' => 'Nazwa użytkownika',
    'Verification Code' => 'Token weryfikacyjny',
    'Verify email token cannot be blank.' => 'Token weryfikacji adresu e-mail nie może być pusty.',
    'Wrong password reset token.' => 'Błędny token resetowania hasła.',
    'You must solve reCAPTCHA in order to continue.' => 'Aby kontynuować, musisz rozwiązać test reCAPTCHA.',
    'Your email is already verified. No further action is needed.' => 'Twój adres e-mail jest już zweryfikowany. Nie musisz już nic więcej robić.',
    'Your own account must remain active.' => 'Twoje konto musi pozostać aktywne.',
];
