<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Examination' => 'Dodaj badanie',
    'Add Patient' => 'Dodaj pacjenta',
    'Add Result' => 'Dodaj wynik',
    'All rights reserved' => 'Wszelkie prawa zastrzeżone',
    'Are you sure you want to delete this examination?' => 'Czy na pewno chcesz usunąć to badanie?',
    'Are you sure you want to delete this patient?' => 'Czy na pewno chcesz usunąć tego pacjenta?',
    'Are you sure you want to delete this result?' => 'Czy na pewno chcesz usunąć ten wynik?',
    'Control Panel' => 'Panel sterowania',
    'Copyright &copy; 2022-{current-year} by' => 'Prawa autorskie &copy; 2022-{current-year}',
    'Delete' => 'Usuń',
    'English' => 'English',
    'European Funds icons' => 'Ikony Funduszy Unijnych',
    'Examination' => 'Badanie',
    'Examinations' => 'Badania',
    'Forgotten password?' => 'Zapomniane hasło?',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Innowacyjne rozwiązania w zakresie zdalnego monitorowania i rehabilitacji wad postawy',
    'Login' => 'Logowanie',
    'Logout' => 'Wyloguj się',
    'Operator' => 'Operator',
    'Patient' => 'Pacjent',
    'Patients' => 'Pacjenci',
    'Please choose your new password:' => 'Proszę wybrać nowe hasło:',
    'Please contact us if you think this is a server error. Thank you.' => 'Jeśli uważasz, że jest to błąd serwera, skontaktuj się z nami. Dziękujemy.',
    'Please fill out the following fields to login:' => 'Aby zalogować się, wypełnij poniższy formularz:',
    'Please fill out the following fields to signup:' => 'Aby się zarejestrować, wypełnij poniższe pola:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą zresetowanie hasła.',
    'Please fill out your email. A verification email will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą weryfikację tego adresu.',
    'Recently added examinations' => 'Ostatnio dodane badania',
    'Recently added patients' => 'Ostatnio dodani pacjenci',
    'Recently added results' => 'Ostatnio dodane wyniki',
    'Register it' => 'Zarejestruj nowe',
    'Request password reset' => 'Reset hasła',
    'Resend it' => 'Ponów wysyłkę',
    'Resend verification email' => 'Weryfikacja adresu e-mail',
    'Reset it' => 'Zresetuj je',
    'Reset password' => 'Reset hasła',
    'Result' => 'Wynik',
    'Results' => 'Wyniki',
    'Save' => 'Zapisz',
    'Send' => 'Wyślij',
    'Signup' => 'Rejestracja',
    'Start' => 'Start',
    'The above error occurred while the Web server was processing your request.' => 'Powyższy błąd wystąpił podczas przetwarzania Twojego żądania przez serwer WWW.',
    'The list of all examinations performed through the system is shown below.' => 'Lista wszystkich badań przeprowadzonych w systemie znajduje się poniżej.',
    'The list of all patients registered in the system is shown below.' => 'Lista wszystkich pacjentów zarejestrowanych w systemie znajduje się poniżej.',
    'The list of all results gathered in the system is shown below.' => 'Lista wszystkich wyników zebranych w systemie znajduje się poniżej.',
    'The verification email did not arrive?' => 'Brak e-maila weryfikacyjnego?',
    'Update' => 'Edytuj',
    'Version' => 'Wersja',
    'View examinations' => 'Przeglądaj badania',
    'View patients' => 'Przeglądaj pacjentów',
    'View results' => 'Przeglądaj wyniki',
    'You do not have an account?' => 'Nie posiadasz konta?',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'Русский' => 'Русский',
    'Details of selected examination are provided below.' => 'Szczegóły wybranego badania podane są poniżej.',
    'Details of selected patient are provided below.' => 'Szczegóły wybranego pacjenta podane są poniżej.',
    'Details of selected result are provided below.' => 'Szczegóły wybranego wyniku podane są poniżej.',
    'Please fill out the following fields to add a patient.' => 'Aby dodać nowego pacjenta, wypełnij poniższy formularz.',
    'Please fill out the following fields to add a result.' => 'Aby dodać nowy wynik, wypełnij poniższy formularz.',
    'Please fill out the following fields to add an examination.' => 'Aby dodać nowe badanie, wypełnij poniższy formularz.',
    'Please use this form to update selected examination.' => 'Aby zmienić dane wybranego badania, użyj poniższego formularza.',
    'Please use this form to update selected patient.' => 'Aby zmienić dane wybranego pacjenta, użyj poniższego formularza.',
    'Please use this form to update selected result.' => 'Aby zmienić dane wybranego wyniku, użyj poniższego formularza.',
];
