<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration' => 'Rejestracja konta',
    'Email Address' => 'Adres e-mail',
    'Password' => 'Hasło',
    'Password reset' => 'Reset hasła',
    'Password reset token cannot be blank.' => 'Token resetowania hasła nie może być pusty.',
    'There is no user with this email address.' => 'Brak użytkownika o podanym adresie e-mail.',
    'This email address has already been taken.' => 'Użytkownik o takim adresie e-mail już istnieje.',
    'This field cannot be blank.' => 'To pole nie może pozostać puste.',
    'This field must contain a valid e-mail address.' => 'To pole musi zawierać prawidłowy adres e-mail.',
    'This username has already been taken.' => 'Użytkownik o takiej nazwie już istnieje.',
    'Username' => 'Nazwa użytkownika',
    'Verification Code' => 'Token weryfikacyjny',
    'Verify email token cannot be blank.' => 'Token weryfikacji adresu e-mail nie może być pusty.',
    'Wrong password reset token.' => 'Błędny token resetowania hasła.',
];
