<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => 'Sprawdź swoją pocztę e-mail, aby uzyskać dalsze instrukcje.',
    'New password saved.' => 'Nowe hasło zostało zapisane.',
    'Only administrators can delete users.' => 'Tylko administratorzy mogą usuwać użytkowników.',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Przepraszamy, ale nie możemy ponownie wysłać wiadomości weryfikacyjnej na podany adres e-mail.',
    'Sorry, we are unable to reset password for the provided email address.' => 'Przepraszamy, ale nie możemy zresetować hasła dla podanego adresu e-mail.',
    'Sorry, we are unable to verify your account with provided token.' => 'Przepraszamy, ale nie możemy zweryfikować Twojego konta za pomocą podanego tokena.',
    'The requested page does not exist.' => 'Wskazana strona nie istnieje.',
    'You cannot delete currently logged-in user.' => 'Nie możesz usunąć aktualnie zalogowanego użytkownika.',
    'You cannot delete last administrator.' => 'Nie możesz usunąć ostatniego administratora.',
    'Your email has been confirmed!' => 'Twój email został potwierdzony!',
    'Welcome aboard! We’ve sent a verification email to your inbox. If you don’t see it, be sure to check your spam or junk folder — just in case.' => 'Witamy na pokładzie! Wysłaliśmy e-mail weryfikacyjny na Twoją skrzynkę. Jeśli go nie widzisz, sprawdź folder spam lub inne zakładki — na wszelki wypadek.',
    'You’ve successfully logged out. For added security, consider closing all browser windows.' => 'Wylogowano pomyślnie. Dla większego bezpieczeństwa warto zamknąć wszystkie okna przeglądarki.',
];
