<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please click the link in your email to confirm your account.' => 'Kliknij link w wiadomości e-mail, aby potwierdzić swoje konto.',
    'The requested page does not exist.' => 'Wskazana strona nie istnieje.',
    'Unfortunately, we can’t resend the verification email to this address.' => 'Niestety nie możemy ponownie wysłać wiadomości weryfikacyjnej na ten adres.',
    'Unfortunately, we can’t reset the password for this email address.' => 'Niestety nie możemy zresetować hasła dla Twojego adresu e-mail.',
    'Unfortunately, we can’t verify your account with the token provided. If the link has expired, try requesting a new one.' => 'Niestety nie możemy zweryfikować Twojego konta za pomocą podanego tokena. Jeśli odnośnik stracił ważność, spróbuj wygenerować nowy.',
    'Welcome aboard! We’ve sent a verification email to your inbox. If you don’t see it, be sure to check your spam or junk folder — just in case.' => 'Witamy na pokładzie! Wysłaliśmy e-mail weryfikacyjny na Twoją skrzynkę. Jeśli go nie widzisz, sprawdź folder spam lub inne zakładki — na wszelki wypadek.',
    'You cannot delete currently logged-in user.' => 'Nie możesz usunąć aktualnie zalogowanego użytkownika.',
    'Your email address has been confirmed!' => 'Twój adres e-mail został potwierdzony!',
    'Your password has been changed successfully.' => 'Twoje hasło zostało pomyślnie zmienione.',
    'You’ve successfully logged out. For added security, consider closing all browser windows.' => 'Wylogowano pomyślnie. Dla większego bezpieczeństwa warto zamknąć wszystkie okna przeglądarki.',
    'Only administrators can delete users.' => 'Tylko administratorzy mogą usuwać użytkowników.',
    'You cannot delete last administrator.' => 'Nie możesz usunąć ostatniego administratora.',
];
