<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' to access all the features and create your unforgettable story.' => ', aby uzyskać dostęp do wszystkich funkcji i stworzyć swoją niezapomnianą historię.',
    'Add User' => 'Dodaj użytkownika',
    'Are you sure you want to delete this user?' => 'Czy na pewno chcesz usunąć tego użytkownika?',
    'Delete' => 'Usuń',
    'Details of selected user are provided below.' => 'Szczegóły wybranego użytkownika podane są poniżej.',
    'Didn’t get the verification email?' => 'Nie dotarł e-mail weryfikacyjny?',
    'Don’t have an account?' => 'Nie masz konta?',
    'English' => 'English',
    'Forgot your password?' => 'Nie pamiętasz hasła?',
    'Log In' => 'Zaloguj się',
    'Log Out' => 'Wyloguj się',
    'Log in' => 'Zaloguj się',
    'Login' => 'Logowanie',
    'Please choose your new password:' => 'Proszę wybrać nowe hasło:',
    'Please contact us if you think this is a server error. Thank you.' => 'Jeśli uważasz, że jest to błąd serwera, skontaktuj się z nami. Dziękujemy.',
    'Please fill in the fields below to create your account.' => 'Wypełnij poniższe pola, aby utworzyć konto.',
    'Please fill out the following fields to add a user.' => 'Aby dodać nowego użytkownika, wypełnij poniższy formularz.',
    'Please provide your email. A link to reset password will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą zresetowanie hasła.',
    'Please provide your email. A verification email will be sent there.' => 'Podaj swój adres e-mail, aby otrzymać wiadomość umożliwiającą weryfikację tego adresu.',
    'Please use this form to update selected user.' => 'Aby zmienić dane wybranego użytkownika, użyj poniższego formularza.',
    'Request password reset' => 'Reset hasła',
    'Resend it' => 'Wyślij go ponownie',
    'Resend verification email' => 'Weryfikacja adresu e-mail',
    'Reset it' => 'Zresetuj je',
    'Reset password' => 'Reset hasła',
    'Save' => 'Zapisz',
    'Send' => 'Wyślij',
    'Sign Up' => 'Zarejestruj się',
    'Sign up now' => 'Zarejestruj się teraz',
    'The above error occurred while server was processing your request.' => 'Powyższy błąd wystąpił podczas przetwarzania Twojego żądania przez serwer.',
    'The list of all users existing in the system is shown below.' => 'Lista wszystkich użytkowników istniejących w systemie znajduje się poniżej.',
    'This user' => 'Ten użytkownik',
    'Update' => 'Edytuj',
    'User' => 'Użytkownik',
    'Users' => 'Użytkownicy',
    'Version' => 'Wersja',
    'Where visual novels and gamebooks begin their journey' => 'Gdzie powieści wizualne i gry paragrafowe rozpoczynają swoją podróż',
    'You can only delete a user that has' => 'Możesz usunąć tylko użytkownika, który',
    'You must assign all user’s objects to some other user before deleting it.' => 'Musisz przypisać wszystkie obiekty danego użytkownika do innego, zanim go usuniesz.',
    'and' => 'i',
    'assigned to itself' => 'przypisanych do siebie',
    'can log in' => 'może się zalogować',
    'cannot log in' => 'nie może się zalogować',
    'is active' => 'jest aktywny',
    'is not active' => 'jest nieaktywny',
    'no objects' => 'żadnych obiektów',
    'polski' => 'polski',
    'to this application' => 'do tej aplikacji',
];
