name: Task (YAML)
description: Plan or track a unit of work
title: ""
labels: []
assignees:
  - mrfatguy
type: task
body:
  - type: markdown
    attributes:
      value: |
        This issue type is meant for simple work items or subtasks. Keep it short and actionable.

  - type: input
    id: summary
    attributes:
      label: Task summary
      description: A one-liner description of the task
      placeholder: e.g., Refactor login form validation
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details or subtasks
      description: Optional — use checkboxes or notes to break the task down
      placeholder: |
        - [ ] Item 1
        - [ ] Item 2