<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Command' => 'Добавить команду',
    'Add Device' => 'Добавить устройство',
    'Add User' => 'Добавить пользователя',
    'Added' => 'Добавлен',
    'All rights reserved' => 'Все права защищены',
    'Are you sure you want to delete this command?' => 'Вы уверены, что хотите удалить эту команду?',
    'Are you sure you want to delete this device?' => 'Вы уверены, что хотите удалить это устройство?',
    'Are you sure you want to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя?',
    'Command' => 'Команда',
    'Commands' => 'Команды',
    'Control Panel' => 'Панель управления',
    'Copyright &copy; 2022-{current-year} by' => 'Авторские права принадлежат &copy; 2022-{current-year}',
    'Delete' => 'Удалить',
    'Details of selected command are provided below.' => 'Подробная информация о выбранной команде представлена ниже.',
    'Details of selected device are provided below.' => 'Подробная информация о выбранном устройстве представлена ниже.',
    'Details of selected user are provided below.' => 'Подробная информация о выбранном пользователе представлена ниже.',
    'Device' => 'Устройство',
    'Devices' => 'Устройства',
    'English' => 'English',
    'European Funds icons' => 'Иконки европейских фондов',
    'If you do not have an account, did not receive the verification email or have forgotten your password, please contact your system administrator. These kinds of situations must be solved manually.' => 'Если у вас нет учетной записи, вы не получили электронное письмо с подтверждением или забыли свой пароль, обратитесь к своему системному администратору. Подобные ситуации приходится решать вручную.',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Инновационный дистанционный мониторинг и реабилитация дефектов осанки',
    'Last contact' => 'Последний контакт',
    'Login' => 'Авторизоваться',
    'Logout' => 'Выйти',
    'Main Application' => 'Основное приложение',
    'Name and surname' => 'Имя и фамилия',
    'Only logged-in users with administrator status have access to the backend. Login is also independent between the backend and the frontend. The person logged in to the backend must also log in to the backend.' => 'Только авторизованные пользователи со статусом администратора имеют доступ к серверной части. Вход в систему также независим между серверной и внешней частью. Человек, вошедший в серверную часть, также должен войти в серверную часть.',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете, что это ошибка сервера. Спасибо.',
    'Please fill out the following fields to add a command.' => 'Пожалуйста, заполните следующие поля, чтобы добавить команду.',
    'Please fill out the following fields to add a device.' => 'Пожалуйста, заполните следующие поля, чтобы добавить устройство.',
    'Please fill out the following fields to add a user.' => 'Пожалуйста, заполните следующие поля, чтобы добавить пользователя.',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Please use this form to update selected command.' => 'Пожалуйста, используйте эту форму для обновления выбранной команды.',
    'Please use this form to update selected device.' => 'Пожалуйста, используйте эту форму для обновления выбранного устройства.',
    'Please use this form to update selected user.' => 'Пожалуйста, используйте эту форму, чтобы обновить выбранного пользователя.',
    'Recently added devices' => 'Недавно добавленные устройства',
    'Recently added users' => 'Недавно добавленные пользователи',
    'Recently parsed commands' => 'Недавно проанализированные команды',
    'Save' => 'Сохранять',
    'Start' => 'Начинать',
    'The above error occurred while the Web server was processing your request.' => 'Вышеупомянутая ошибка произошла во время обработки вашего запроса веб-сервером.',
    'The list of all commands created in the system is shown below.' => 'Список всех команд, созданных в системе, показан ниже.',
    'The list of all devices existing in the system is shown below.' => 'Список всех устройств, существующих в системе, показан ниже.',
    'The list of all users existing in the system is shown below.' => 'Список всех пользователей, существующих в системе, показан ниже.',
    'This user' => 'Этот пользователь',
    'This user has' => 'У этого пользователя есть',
    'Update' => 'Обновлять',
    'Update Device: {name}' => 'Обновить устройство: {name}',
    'User' => 'Пользователь',
    'Users' => 'Пользователи',
    'Version' => 'Версия',
    'View commands' => 'Просмотр команд',
    'View devices' => 'Просмотр устройств',
    'View users' => 'Просмотр пользователей',
    'and' => 'и',
    'and therefore' => 'и поэтому',
    'can be deleted' => 'можно удалить',
    'can login' => 'можно войти',
    'cannot be deleted' => 'невозможно удалить',
    'cannot login' => 'hе можете войти',
    'is active' => 'активен',
    'is an administrator' => 'является администратором',
    'is not active' => 'не активен',
    'is not an administrator' => 'не администратор',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'to backend' => 'на панель управления',
    'to frontend' => 'в основное приложение',
    '{p, plural, =0{no examinations} =1{# examination} other{# examinations}}' => '{p, plural, =0{нет исследований} =1{# исследований} few{# исследований} other{# исследований}}',
    '{p, plural, =0{no patients} =1{# patient} other{# patients}}' => '{p, plural, =0{нет пациентов} =1{# пациент} other{# пациентов}}',
    '{p, plural, =0{no results} =1{# result} other{# results}}' => '{p, plural, =0{нет результатов} =1{# результат} other{# результатов}}',
    'Русский' => 'Русский',
    'You can only delete a user that has' => 'Вы можете удалить только пользователя, у которого есть',
    'You must assign all user\'s objects to some other user before deleting it.' => 'Вы должны назначить все объекты пользователя другому пользователю, прежде чем удалять его.',
    'assigned to itself' => 'присвоенный самому себе',
    'no patients, no examinations and no results' => 'ни пациентов, ни обследований, ни результатов',
];
