<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email address:' => 'Адрес электронной почты:',
    'For the account' => 'Для аккаунта',
    'Have good day!' => 'Хорошего дня!',
    'Hello!' => 'Привет!',
    'If it was you then follow the link below to continue and reset your password:' => 'Если это были вы, перейдите по ссылке ниже, чтобы продолжить и сбросить пароль:',
    'If it was you then follow the link below to verify your email address:' => 'Если это были вы, перейдите по ссылке ниже, чтобы подтвердить свой адрес электронной почты:',
    'If it wasn\'t you then you may safely ignore this message. Unverified email addresses are automatically removed from our system.' => 'Если это были не вы, то можете смело игнорировать это сообщение. Неподтвержденные адреса электронной почты автоматически удаляются из нашей системы.',
    'If it wasn\'t you then you may safely ignore this message. Your password won\'t be changed.' => 'Если это были не вы, то можете смело игнорировать это сообщение. Ваш пароль не будет изменен.',
    'Login:' => 'Логин:',
    'Name and surname:' => 'Имя и фамилия:',
    'Somebody has created an account in our website with the following data:' => 'Кто-то создал учетную запись на нашем сайте со следующими данными:',
    'The {app-name}\'s Team' => 'Команда {app-name}',
    'somebody has requested a password to the be reset.' => 'кто-то запросил пароль для сброса.',
];
