<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You signed out of your account. It\'s a good idea to close all browser windows.' => 'Вы вышли из своей учетной записи. Рекомендуется закрыть все окна браузера.',
    'Check your email for further instructions.' => 'Проверьте свою электронную почту для получения дальнейших инструкций.',
    'New password saved.' => 'Новый пароль сохранен.',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'К сожалению, мы не можем повторно отправить письмо с подтверждением на указанный адрес электронной почты.',
    'Sorry, we are unable to reset password for the provided email address.' => 'К сожалению, мы не можем сбросить пароль для указанного адреса электронной почты.',
    'Sorry, we are unable to verify your account with provided token.' => 'К сожалению, мы не можем подтвердить вашу учетную запись с помощью предоставленного токена.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Спасибо за регистрацию. Пожалуйста, проверьте свой почтовый ящик на наличие письма с подтверждением.',
    'The requested page does not exist.' => 'Запрошенная страница не существует.',
    'Your email has been confirmed!' => 'Ваше сообщение было подтверждено!',
];
