<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration' => 'Регистрация аккаунта',
    'Email Address' => 'Адрес электронной почты',
    'Password' => 'Пароль',
    'Password reset' => 'Восстановление пароля',
    'Password reset token cannot be blank.' => 'Токен сброса пароля не может быть пустым.',
    'There is no user with this email address.' => 'Нет пользователя с таким адресом электронной почты.',
    'This email address has already been taken.' => 'Этот адрес электронной почты уже занят.',
    'This field cannot be blank.' => 'Это поле не может быть пустым.',
    'This field must contain a valid e-mail address.' => 'Поле этого поля должно содержать действительный адрес электронной почты.',
    'This username has already been taken.' => 'Это имя пользователя уже занято.',
    'Username' => 'Имя пользователя',
    'Verification Code' => 'Проверочный код',
    'Verify email token cannot be blank.' => 'Убедитесь, что токен электронной почты не может быть пустым.',
    'Wrong password reset token.' => 'Неправильный токен сброса пароля.',
    'Name' => 'Имя',
    'Surname' => 'Фамилия',
];
