<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Examination' => 'Добавить обследование',
    'Add Patient' => 'Добавить пациента',
    'Add Result' => 'Добавить результат',
    'All rights reserved' => 'Все права защищены',
    'Are you sure you want to delete this examination?' => 'Вы уверены, что хотите удалить это обследование?',
    'Are you sure you want to delete this patient?' => 'Вы уверены, что хотите удалить этого пациента?',
    'Are you sure you want to delete this result?' => 'Вы уверены, что хотите удалить этот результат?',
    'Control Panel' => 'Панель управления',
    'Copyright &copy; 2022-{current-year} by' => 'Авторские права принадлежат &copy; 2022-{current-year}',
    'Delete' => 'Удалить',
    'English' => 'English',
    'European Funds icons' => 'Иконки европейских фондов',
    'Examination' => 'Обследование',
    'Examinations' => 'Бадания',
    'Forgotten password?' => 'Забытый пароль?',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Инновационный дистанционный мониторинг и реабилитация дефектов осанки',
    'Login' => 'Авторизоваться',
    'Logout' => 'Выйти',
    'Operator' => 'Оператор',
    'Patient' => 'Пациент',
    'Patients' => 'Пациенты',
    'Please choose your new password:' => 'Пожалуйста, выберите новый пароль:',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете, что это ошибка сервера. Спасибо.',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Please fill out the following fields to signup:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Please fill out your email. A link to reset password will be sent there.' => 'аренду заполните свой адрес электронной почты. Туда будет отправлена ссылка для сброса пароля.',
    'Please fill out your email. A verification email will be sent there.' => 'Пожалуйста, заполните свой адрес электронной почты. Туда будет отправлено письмо с подтверждением.',
    'Recently added examinations' => 'Недавно добавленные обследования',
    'Recently added patients' => 'Недавно добавленные пациенты',
    'Recently added results' => 'Недавно добавленные результаты',
    'Register it' => 'Зарегистрируйте один',
    'Request password reset' => 'Запросить сброс пароля',
    'Resend it' => 'Перешли Это',
    'Resend verification email' => 'Выслать повторно письмо для подтверждения',
    'Reset it' => 'Сбросить настройки',
    'Reset password' => 'Сброс пароля',
    'Result' => 'Результат',
    'Results' => 'Результаты',
    'Save' => 'Сохранять',
    'Send' => 'Отправлять',
    'Signup' => 'Зарегистрироваться',
    'Start' => 'Начинать',
    'The above error occurred while the Web server was processing your request.' => 'Вышеупомянутая ошибка произошла во время обработки вашего запроса веб-сервером.',
    'The list of all examinations performed through the system is shown below.' => 'Список всех обследований, проводимых через систему, представлен ниже.',
    'The list of all patients registered in the system is shown below.' => 'Список всех пациентов, зарегистрированных в системе, представлен ниже.',
    'The list of all results gathered in the system is shown below.' => 'Список всех результатов, собранных в системе, показан ниже.',
    'The verification email did not arrive?' => 'Письмо с подтверждением не пришло?',
    'Update' => 'Обновлять',
    'Version' => 'Версия',
    'View examinations' => 'Посмотреть обследования',
    'View patients' => 'Просмотр пациентов',
    'View results' => 'Посмотреть Результаты',
    'You do not have an account?' => 'У вас нет аккаунта?',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'Русский' => 'Русский',
    'Details of selected examination are provided below.' => 'Подробная информация о выбранном обследовании представлена ниже.',
    'Details of selected patient are provided below.' => 'Подробная информация о выбранном пациенте представлена ниже.',
    'Details of selected result are provided below.' => 'Подробная информация о выбранном результате представлена ниже.',
    'Please fill out the following fields to add a patient.' => 'Пожалуйста, заполните следующие поля, чтобы добавить пациента.',
    'Please fill out the following fields to add a result.' => 'Пожалуйста, заполните следующие поля, чтобы добавить результат.',
    'Please fill out the following fields to add an examination.' => 'Пожалуйста, заполните следующие поля, чтобы добавить обследование.',
    'Please use this form to update selected examination.' => 'Пожалуйста, используйте эту форму, чтобы обновить выбранное обследование.',
    'Please use this form to update selected patient.' => 'Пожалуйста, используйте эту форму, чтобы обновить информацию о выбранном пациенте.',
    'Please use this form to update selected result.' => 'Пожалуйста, используйте эту форму, чтобы обновить выбранный результат.',
];
