<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Command' => 'Pridať príkaz',
    'Add Device' => 'Pridať zariadenie',
    'Add User' => 'Pridať používateľa',
    'Added' => 'Pridané',
    'All rights reserved' => 'Všetky práva vyhradené',
    'Are you sure you want to delete this command?' => 'Naozaj chcete odstrániť tento príkaz?',
    'Are you sure you want to delete this device?' => 'Naozaj chcete odstrániť toto zariadenie?',
    'Are you sure you want to delete this user?' => 'Naozaj chcete odstrániť tohto používateľa?',
    'Command' => 'Príkaz',
    'Commands' => 'Príkazy',
    'Control Panel' => 'Ovládací panel',
    'Copyright &copy; 2022-{current-year} by' => 'Autorské práva od &copy; 2022-{current-year}',
    'Delete' => 'Odstrániť',
    'Details of selected command are provided below.' => 'Podrobnosti o vybranom príkaze sú uvedené nižšie.',
    'Details of selected device are provided below.' => 'Podrobnosti o vybranom zariadení sú uvedené nižšie.',
    'Details of selected user are provided below.' => 'Podrobnosti o vybranom používateľovi sú uvedené nižšie.',
    'Device' => 'Zariadenie',
    'Devices' => 'Zariadenia',
    'English' => 'English',
    'European Funds icons' => 'Ikony európskych fondov',
    'If you do not have an account, did not receive the verification email or have forgotten your password, please contact your system administrator. These kinds of situations must be solved manually.' => 'Ak nemáte účet, nedostali ste overovací e-mail alebo ste zabudli svoje heslo, obráťte sa na správcu systému. Takéto situácie sa musia riešiť manuálne.',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Inovatívne riešenia pre vzdialené monitorovanie a rehabilitáciu posturálnych defektov',
    'Last contact' => 'Posledný kontakt',
    'Login' => 'Prihlásiť sa',
    'Logout' => 'Odhlásiť sa',
    'Main Application' => 'Hlavná aplikácia',
    'Name and surname' => 'Meno a priezvisko',
    'Only logged-in users with administrator status have access to the backend. Login is also independent between the backend and the frontend. The person logged in to the backend must also log in to the backend.' => 'Prístup k backendu majú iba prihlásení používatelia so statusom správcu. Prihlásenie je tiež nezávislé medzi backendom a frontendom. Osoba prihlásená do backendu sa musí prihlásiť aj do backendu.',
    'Please contact us if you think this is a server error. Thank you.' => 'Ak si myslíte, že ide o chybu servera, kontaktujte nás. Ďakujem.',
    'Please fill out the following fields to add a command.' => 'Ak chcete pridať príkaz, vyplňte nasledujúce polia.',
    'Please fill out the following fields to add a device.' => 'Ak chcete pridať zariadenie, vyplňte nasledujúce polia.',
    'Please fill out the following fields to add a user.' => 'Ak chcete pridať používateľa, vyplňte nasledujúce polia.',
    'Please fill out the following fields to login:' => 'Pre prihlásenie vyplňte prosím nasledujúce polia:',
    'Please use this form to update selected command.' => 'Na aktualizáciu vybraného príkazu použite tento formulár.',
    'Please use this form to update selected device.' => 'Na aktualizáciu vybraného zariadenia použite tento formulár.',
    'Please use this form to update selected user.' => 'Na aktualizáciu vybraného používateľa použite tento formulár.',
    'Recently added devices' => 'Nedávno pridané zariadenia',
    'Recently added users' => 'Nedávno pridaní používatelia',
    'Recently parsed commands' => 'Nedávno analyzované príkazy',
    'Save' => 'Uložiť',
    'Start' => 'Štart',
    'The above error occurred while the Web server was processing your request.' => 'Vyššie uvedená chyba sa vyskytla, keď webový server spracovával vašu požiadavku.',
    'The list of all commands created in the system is shown below.' => 'Zoznam všetkých príkazov vytvorených v systéme je uvedený nižšie.',
    'The list of all devices existing in the system is shown below.' => 'Zoznam všetkých zariadení existujúcich v systéme je uvedený nižšie.',
    'The list of all users existing in the system is shown below.' => 'Zoznam všetkých používateľov existujúcich v systéme je uvedený nižšie.',
    'This user' => 'Tento používateľ',
    'This user has' => 'Tento používateľ má',
    'Update' => 'Aktualizovať',
    'Update Device: {name}' => 'Aktualizovať zariadenie: {name}',
    'User' => 'Používateľ',
    'Users' => 'Používatelia',
    'Version' => 'Verzia',
    'View commands' => 'Zobraziť príkazy',
    'View devices' => 'Zobraziť zariadenia',
    'View users' => 'Zobraziť používateľov',
    'and' => 'a',
    'and therefore' => 'a preto',
    'can be deleted' => 'možno vymazať',
    'can login' => 'môže sa prihlásiť',
    'cannot be deleted' => 'nemožno odstrániť',
    'cannot login' => 'nemôže sa prihlásiť',
    'is active' => 'je aktívny',
    'is an administrator' => 'je správcom',
    'is not active' => 'nie je aktívny',
    'is not an administrator' => 'nie je správcom',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'to backend' => 'na ovládací panel',
    'to frontend' => 'do hlavnej aplikácie',
    '{p, plural, =0{no examinations} =1{# examination} other{# examinations}}' => '{p, plural, =0{žiadny výskum} =1{má # prieskum} few{má # prieskum} other{má # prieskum}}',
    '{p, plural, =0{no patients} =1{# patient} other{# patients}}' => '{p, plural, =0{žiadni pacienti} =1{# pacient} other{# pacienti}}',
    '{p, plural, =0{no results} =1{# result} other{# results}}' => '{p, plural, =0{žiadne výsledky} =1{# výsledok} other{# výsledkov}}',
    'Русский' => 'Русский',
    'You can only delete a user that has' => 'Môžete odstrániť iba používateľa, ktorý má',
    'You must assign all user\'s objects to some other user before deleting it.' => 'Pred odstránením musíte priradiť všetky objekty používateľa nejakému inému používateľovi.',
    'assigned to itself' => 'pridelené sebe',
    'no patients, no examinations and no results' => 'žiadni pacienti, žiadne vyšetrenia a žiadne výsledky',
];
