<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email address:' => 'Emailová adresa:',
    'For the account' => 'Pre účet',
    'Have good day!' => 'Pekný deň!',
    'Hello!' => 'Ahoj!',
    'If it was you then follow the link below to continue and reset your password:' => 'Ak ste to boli vy, pokračujte kliknutím na odkaz nižšie a obnovte svoje heslo:',
    'If it was you then follow the link below to verify your email address:' => 'Ak ste to boli vy, kliknite na odkaz nižšie a overte svoju e-mailovú adresu:',
    'If it wasn\'t you then you may safely ignore this message. Unverified email addresses are automatically removed from our system.' => 'Ak ste to neboli vy, môžete túto správu pokojne ignorovať. Neoverené e-mailové adresy sú z nášho systému automaticky odstránené.',
    'If it wasn\'t you then you may safely ignore this message. Your password won\'t be changed.' => 'Ak ste to neboli vy, môžete túto správu pokojne ignorovať. Vaše heslo sa nezmení.',
    'Login:' => 'Prihlasovacie meno:',
    'Name and surname:' => 'Meno a priezvisko:',
    'Somebody has created an account in our website with the following data:' => 'Niekto si na našej webovej stránke vytvoril účet s nasledujúcimi údajmi:',
    'The {app-name}\'s Team' => 'Tím spoločnosti {app-name}',
    'somebody has requested a password to the be reset.' => 'niekto si vyžiadal heslo na obnovenie.',
];
