<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account registration' => 'Registrácia účtu',
    'Email Address' => 'Emailová adresa',
    'Password' => 'Heslo',
    'Password reset' => 'Resetovanie hesla',
    'Password reset token cannot be blank.' => 'Token na obnovenie hesla nemôže byť prázdny.',
    'There is no user with this email address.' => 'Neexistuje žiadny používateľ s touto e-mailovou adresou.',
    'This email address has already been taken.' => 'Táto e-mailová adresa už bola obsadená.',
    'This field cannot be blank.' => 'Toto pole nemôže byť prázdne.',
    'This field must contain a valid e-mail address.' => 'Toto pole musí obsahovať platnú e-mailovú adresu.',
    'This username has already been taken.' => 'Toto používateľské meno je už obsadené.',
    'Username' => 'Používateľské meno',
    'Verification Code' => 'Overovací kód',
    'Verify email token cannot be blank.' => 'E-mailový token nemôže byť prázdny.',
    'Wrong password reset token.' => 'Nesprávny token na obnovenie hesla.',
    'Name' => 'Názov',
    'Surname' => 'Priezvisko',
];
