<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You signed out of your account. It\'s a good idea to close all browser windows.' => 'Odhlásili ste sa zo svojho účtu. Je dobré zavrieť všetky okná prehliadača.',
    'Check your email for further instructions.' => 'Ďalšie pokyny nájdete vo svojom e-maile.',
    'New password saved.' => 'Nové heslo bolo uložené.',
    'Sorry, we are unable to resend verification email for the provided email address.' => 'Ľutujeme, ale nemôžeme znova odoslať overovací e-mail na uvedenú e-mailovú adresu.',
    'Sorry, we are unable to reset password for the provided email address.' => 'Ľutujeme, ale nemôžeme obnoviť heslo pre zadanú e-mailovú adresu.',
    'Sorry, we are unable to verify your account with provided token.' => 'Ľutujeme, ale pomocou poskytnutého tokenu nemôžeme overiť váš účet.',
    'Thank you for registration. Please check your inbox for verification email.' => 'Ďakujeme za registráciu. Skontrolujte si v doručenej pošte overovací e-mail.',
    'The requested page does not exist.' => 'Požadovaná stránka neexistuje.',
    'Your email has been confirmed!' => 'Váš email bol potvrdený!',
];
