<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Examination' => 'Pridať skúšku',
    'Add Patient' => 'Pridať pacienta',
    'Add Result' => 'Pridať výsledok',
    'All rights reserved' => 'Všetky práva vyhradené',
    'Are you sure you want to delete this examination?' => 'Naozaj chcete odstrániť toto vyšetrenie?',
    'Are you sure you want to delete this patient?' => 'Naozaj chcete odstrániť tohto pacienta?',
    'Are you sure you want to delete this result?' => 'Naozaj chcete odstrániť tento výsledok?',
    'Control Panel' => 'Ovládací panel',
    'Copyright &copy; 2022-{current-year} by' => 'Autorské práva od &copy; 2022-{current-year}',
    'Delete' => 'Odstrániť',
    'English' => 'English',
    'European Funds icons' => 'Ikony európskych fondov',
    'Examination' => 'Vyšetrenie',
    'Examinations' => 'Skúšky',
    'Forgotten password?' => 'Zabudnuté heslo?',
    'Innovative solutions for remote monitoring and rehabilitation of postural defects' => 'Inovatívne riešenia pre vzdialené monitorovanie a rehabilitáciu posturálnych defektov',
    'Login' => 'Prihlásiť sa',
    'Logout' => 'Odhlásiť sa',
    'Operator' => 'Operátor',
    'Patient' => 'Pacient',
    'Patients' => 'Pacientov',
    'Please choose your new password:' => 'Vyberte si svoje nové heslo:',
    'Please contact us if you think this is a server error. Thank you.' => 'Ak si myslíte, že ide o chybu servera, kontaktujte nás. Ďakujem.',
    'Please fill out the following fields to login:' => 'Pre prihlásenie vyplňte prosím nasledujúce polia:',
    'Please fill out the following fields to signup:' => 'Ak sa chcete zaregistrovať, vyplňte nasledujúce polia:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Vyplňte prosím svoj email. Bude tam odoslaný odkaz na obnovenie hesla.',
    'Please fill out your email. A verification email will be sent there.' => 'Vyplňte prosím svoj email. Bude tam odoslaný overovací e-mail.',
    'Recently added examinations' => 'Nedávno pridané skúšky',
    'Recently added patients' => 'Nedávno pridaní pacienti',
    'Recently added results' => 'Nedávno pridané výsledky',
    'Register it' => 'Zaregistrujte sa',
    'Request password reset' => 'Požiadať o obnovenie hesla',
    'Resend it' => 'Pošlite to znova',
    'Resend verification email' => 'Opätovné zaslanie overovacieho e-mailu',
    'Reset it' => 'Obnovte ho',
    'Reset password' => 'Obnoviť heslo',
    'Result' => 'Výsledok',
    'Results' => 'Výsledky',
    'Save' => 'Uložiť',
    'Send' => 'Odoslať',
    'Signup' => 'Prihlásiť Se',
    'Start' => 'Štart',
    'The above error occurred while the Web server was processing your request.' => 'Vyššie uvedená chyba sa vyskytla, keď webový server spracovával vašu požiadavku.',
    'The list of all examinations performed through the system is shown below.' => 'Zoznam všetkých vyšetrení vykonaných prostredníctvom systému je uvedený nižšie.',
    'The list of all patients registered in the system is shown below.' => 'Zoznam všetkých pacientov registrovaných v systéme je uvedený nižšie.',
    'The list of all results gathered in the system is shown below.' => 'Zoznam všetkých výsledkov zhromaždených v systéme je uvedený nižšie.',
    'The verification email did not arrive?' => 'Overovací email neprišiel?',
    'Update' => 'Aktualizovať',
    'Version' => 'Verzia',
    'View examinations' => 'Pozrite si skúšky',
    'View patients' => 'Pozrite si pacientov',
    'View results' => 'Zobraziť výsledky',
    'You do not have an account?' => 'Nemáte účet?',
    'polski' => 'polski',
    'slovenský' => 'slovenský',
    'Русский' => 'Русский',
    'Details of selected examination are provided below.' => 'Podrobnosti o vybranom vyšetrení sú uvedené nižšie.',
    'Details of selected patient are provided below.' => 'Podrobnosti o vybranom pacientovi sú uvedené nižšie.',
    'Details of selected result are provided below.' => 'Podrobnosti o vybranom výsledku sú uvedené nižšie.',
    'Please fill out the following fields to add a patient.' => 'Ak chcete pridať pacienta, vyplňte nasledujúce polia.',
    'Please fill out the following fields to add a result.' => 'Ak chcete pridať výsledok, vyplňte nasledujúce polia.',
    'Please fill out the following fields to add an examination.' => 'Ak chcete pridať skúšku, vyplňte nasledujúce polia.',
    'Please use this form to update selected examination.' => 'Na aktualizáciu vybraného vyšetrenia použite tento formulár.',
    'Please use this form to update selected patient.' => 'Na aktualizáciu vybraného pacienta použite tento formulár.',
    'Please use this form to update selected result.' => 'Ak chcete aktualizovať vybraný výsledok, použite tento formulár.',
];
